<?php

include_once ('Cha.php');
class Cha extends Ong
{
    public $hat;

    public function __construct($age, $hat)
    {
        parent::__construct($age);
        $this->hat = $hat;
    }
    public function Run()
    {
        return parent::Run(); // TODO: Change the autogenerated stub
    }

    public function Hat(){
        return "123";
    }

}