<?php

include_once('Cha.php');

class Con extends Cha
{
    public function __construct($age, $hat)
    {
        parent::__construct($age, $hat);
    }

    public function Run()
    {
        return parent::Run();// TODO: Change the autogenerated stub
    }
    public function Hat()
    {
        return parent::Hat(); // TODO: Change the autogenerated stub
    }
}